// File generated by Gemma 4 e4b
import { Sequelize, ModelStatic, InferCreationAttributes, InferAttributes } from 'sequelize';
import { ToolCallHist } from '../models/ToolCallHist';
import { type Logger } from 'pino';
import type Store from './store';

type ToolCallHistCreateInput = InferCreationAttributes<ToolCallHist>;
type ToolCallHistAttributes = InferAttributes<ToolCallHist>;

export class ToolCallHistService {
  private store: Store;
  private db: Sequelize;
  private logger: Logger;
  private Model: ModelStatic<ToolCallHist>;

  constructor(store: Store, logger: Logger) {
    this.store = store;
    this.db = this.store.db;
    this.logger = logger;
    this.Model = this.db.models.ToolCallHist as ModelStatic<ToolCallHist>;
  }

  /**
   * Creates a new record in the tool call history.
   * @param data The data to create.
   * @returns The created ToolCallHist instance.
   */
  async create(data: ToolCallHistCreateInput): Promise<ToolCallHist> {
    // Basic validation can be added here if needed (e.g., checking required fields)
    const newRecord = await this.Model.create(data);
    this.logger.info(`ToolCallHist created for aftId: ${data.aftId}`);
    return newRecord;
  }

  /**
   * Finds a tool call history record by its primary key (id).
   * @param id The ID of the record.
   * @returns The ToolCallHist instance or null.
   */
  async findById(id: number): Promise<ToolCallHist | null> {
    return this.Model.findByPk(id);
  }

  /**
   * Finds all tool call history records.
   * @returns An array of ToolCallHist instances.
   */
  async findAll(): Promise<ToolCallHist[]> {
    return this.Model.findAll();
  }

  /**
   * Retrieves tool call history records, potentially filtered by AftId.
   * @param aftId The AftId to filter by.
   * @returns An array of ToolCallHist instances.
   */
  async findByAftId(aftId: string): Promise<ToolCallHist | null> {
    return this.Model.findOne({ where: { aftId: aftId } });
  }

  async followTrail(msgId: string): Promise<any[]> {
    const tool_call_data = await this.findByAftId(msgId);
    if (tool_call_data) {
      const next_tool_call_data = await this.followTrail(tool_call_data.id);
      return [tool_call_data.data, ...next_tool_call_data]
    }
    else {
      return []
    }
  }

  /**
   * Updates an existing tool call history record.
   * @param id The ID of the record to update.
   * @param updates Partial data to update.
   * @returns The updated ToolCallHist instance or null.
   */
  async update(id: number, updates: Partial<ToolCallHistAttributes>): Promise<ToolCallHist | null> {
    const inst = await this.findById(id);
    if (!inst) return null;
    const updatedInstance = await inst.update(updates);
    return updatedInstance;
  }

  /**
   * Deletes a tool call history record by its primary key.
   * @param id The ID of the record to delete.
   * @returns A promise that resolves when the record is deleted.
   */
  async destroy(id: number): Promise<void> {
    await this.Model.destroy({ where: { id: id } });
    this.logger.info(`ToolCallHist record deleted with id: ${id}`);
  }
}