import { SnowflakeId } from '@akashrajpurohit/snowflake-id';
import moment from 'moment-timezone';

const generator = SnowflakeId({ workerId: 0, epoch: 0 });

export function getUptime(): string {
  // Original code generated by Gemini via Google Search
  const uptimeInSeconds = process.uptime();
  const days = Math.floor(uptimeInSeconds / (60 * 60 * 24));
  const hours = Math.floor((uptimeInSeconds % (60 * 60 * 24)) / (60 * 60));
  const minutes = Math.floor((uptimeInSeconds % (60 * 60)) / 60);
  const seconds = Math.floor(uptimeInSeconds % 60);
  // const uptimeString = `${days} days, ${hours} hours, ${minutes} minutes, ${seconds} seconds`;
  const datas = [days, hours, minutes, seconds];
  const dataLabels = ['days', 'hours', 'minutes', 'seconds'];
  const uptimeData = new Array();
  for (let i = 0; i < datas.length; i++) {
    if (datas[i] > 0) {
      uptimeData.push(`${datas[i]} ${dataLabels[i]}`)
    }
  }
  return uptimeData.join(', ');
}


export function genErrorTrace(error: Error): string {
  // Reference: https://stackoverflow.com/a/75250999
  return `${error}\n${error.stack?.split("\n").slice(1, 4).join("\n")}`
}

export function genSnowId(): BigInt {
  return BigInt(generator.generate());
}

export function getTime(): number {
  return (new Date()).getTime()
}

export function formatDateTime(date: number | Date) {
  return moment(date).format('DD/MM/YYYY, ddd (HH:mm:ss)')
}

export function parseTimestamp(timestamp: number): string {
  return moment(timestamp).format('DD/MM/YYYY (HH:mm)')
}

// Function generated by ChatGPT
export function convertHoursToReadableTime(totalHours: number) {
  // Convert fractional hours to seconds for precise breakdown
  let totalSeconds = Math.round(totalHours * 3600);

  const secondsInWeek = 7 * 24 * 3600;
  const secondsInDay = 24 * 3600;
  const secondsInHour = 3600;
  const secondsInMinute = 60;

  const weeks = Math.floor(totalSeconds / secondsInWeek);
  totalSeconds %= secondsInWeek;

  const days = Math.floor(totalSeconds / secondsInDay);
  totalSeconds %= secondsInDay;

  const hours = Math.floor(totalSeconds / secondsInHour);
  totalSeconds %= secondsInHour;

  const minutes = Math.floor(totalSeconds / secondsInMinute);
  const seconds = totalSeconds % secondsInMinute;

  const parts = [];

  if (weeks) parts.push(`${weeks} week${weeks !== 1 ? 's' : ''}`);
  if (days) parts.push(`${days} day${days !== 1 ? 's' : ''}`);
  if (hours) parts.push(`${hours} hour${hours !== 1 ? 's' : ''}`);
  if (minutes) parts.push(`${minutes} minute${minutes !== 1 ? 's' : ''}`);
  if (seconds) parts.push(`${seconds} second${seconds !== 1 ? 's' : ''}`);

  return parts.length > 0 ? parts.join(', ') : '0 hours';
}